version:  "2"
services:
  nginx-poc:
    build:
      context: ./nginx_poc
      dockerfile: Dockerfile.nginx
    command: "/usr/sbin/nginx -g 'daemon off;'"
    image: nginx-poc
    ports:
      - "80:80"
    restart: always
