FROM debian:buster

RUN apt-get -y update && \
    apt-get install -y --no-install-recommends \
        nginx \
        less \
        python3 \
        python3-dev \
        python3-pip

COPY nginx.conf /etc/nginx/sites-enabled/poc.conf
RUN rm -f /etc/nginx/sites-enabled/default

RUN mkdir -p /data/www
COPY index.html hello.html /data/www
