FROM debian:buster

RUN apt-get -y update && \
    apt-get install -y --no-install-recommends \
        python3 \
        python3-dev \
        python3-pip

WORKDIR /app

# ARG MAGIC_VALUE_1

RUN echo "MAGIC_VALUE_1=$MAGIC_VALUE_1" >> variables
