version: "2"
services:
  zmq-publisher:
    build:
      context: .
      dockerfile: Dockerfile.pub.zmq
    networks:
      default:
      krusty-krab-2:
        aliases:
          - 'krusty-krab-2'
          - 'krusty-krab-3'
    command: bash
    image: zmq-pub
    # TODO: Uncomment the option below if you want to experiment.
    # network_mode: host
    restart: always
    tty: true
    volumes:
      - ./:/usr/src/app
  zmq-subscriber:
    build:
      context: .
      dockerfile: Dockerfile.sub.zmq
    networks:
      default:
      krusty-krab-2:
    command: bash
    # TODO: Uncomment this option if you want to experiment.
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    image: zmq-sub
    restart: always
    tty: true
    volumes:
      - ./:/usr/src/app
networks:
  krusty-krab-2:
