# @TODO: Refactor common lines into a base image.
FROM balenalib/raspberrypi3:buster

RUN apt-get -y update && \
    apt-get install -y --no-install-recommends \
        libzmq3-dev \
        python3 \
        python3-dev \
        python3-pip

COPY requirements/requirements.main.txt /tmp/requirements.txt
RUN pip3 install --no-cache-dir -r /tmp/requirements.txt

COPY settings.py .

WORKDIR /usr/src/app
COPY ./publisher.py .
