FROM balenalib/raspberrypi3:buster

RUN apt-get -y update && \
    apt-get install -y --no-install-recommends \
        python3 \
        python3-dev \
        python3-pip

WORKDIR /usr/src/app
COPY ./main.py .
