version: "2"
services:
  publisher:
    build:
      context: .
      dockerfile: Dockerfile.publisher
    command: bash
    tty: true
    volumes:
      - ./:/app
  subscriber:
    build:
      context: .
      dockerfile: Dockerfile.subscriber
    command: bash
    tty: true
    volumes:
      - ./:/app
