FROM balenalib/raspberrypi3:buster

RUN apt-get update && \
    apt-get -y install --no-install-recommends \
        vlc && \
    apt-get clean

COPY ./assets/first-youtube-video .

RUN useradd -g video viewer
