FROM balenalib/raspberrypi3:buster

RUN apt-get update && \
    apt-get -y install --no-install-recommends \
        vlc && \
    apt-get clean

WORKDIR /usr/src/app
COPY ./assets/first-youtube-video.mp4 .

RUN useradd -g video viewer
