# FROM balenalib/raspberrypi3:buster
FROM debian:bullseye

RUN apt-get update && \
    apt-get -y install --no-install-recommends \
        vlc
    # apt-get clean

# RUN apt-get update && \
#     apt-get -y install --no-install-recommends \
#         build-essential \
#         ca-certificates \
#         git-core \
#         libasound2-dev \
#         libavcodec-dev \
#         libavformat-dev \
#         libavutil-dev \
#         libbz2-dev \
#         libcec-dev  \
#         libdbus-1-dev \
#         libdbus-glib-1-dev \
#         libdrm-dev \
#         libegl1-mesa-dev \
#         libevent-dev \
#         libffi-dev \
#         libfontconfig1-dev \
#         libfreetype6-dev \
#         libgbm-dev \
#         libgcrypt20-dev \
#         libgles2-mesa \
#         libgles2-mesa-dev \
#         libglib2.0-dev \
#         # libgst-dev \
#         libicu-dev \
#         libinput-dev \
#         libiodbc2-dev \
#         libjpeg62-turbo-dev \
#         libjsoncpp-dev \
#         libminizip-dev \
#         libnss3 \
#         libnss3-dev \
#         libopus-dev \
#         libpci-dev \
#         libpng-dev \
#         libpng16-16 \
#         libpq-dev \
#         libpulse-dev \
#         # libraspberrypi0 \
#         librsvg2-common \
#         libsdl2-dev \
#         libsnappy-dev \
#         libsqlite0-dev \
#         libsqlite3-dev \
#         # libsrtp0-dev \
#         libsrtp2-dev \
#         libssl-dev \
#         libssl1.1 \
#         libswscale-dev \
#         libsystemd-dev \
#         libts-dev \
#         libudev-dev \
#         libvpx-dev \
#         libwebp-dev \
#         libx11-dev \
#         libx11-xcb-dev \
#         libx11-xcb1 \
#         libxcb-glx0-dev \
#         libxcb-icccm4 \
#         libxcb-icccm4-dev \
#         libxcb-image0 \
#         libxcb-image0-dev \
#         libxcb-keysyms1 \
#         libxcb-keysyms1-dev \
#         libxcb-randr0-dev \
#         libxcb-render-util0 \
#         libxcb-render-util0-dev \
#         libxcb-shape0-dev \
#         libxcb-shm0 \
#         libxcb-shm0-dev \
#         libxcb-sync-dev \
#         libxcb-sync1 \
#         libxcb-xfixes0-dev \
#         libxcb-xinerama0 \
#         libxcb-xinerama0-dev \
#         libxcb1 \
#         libxcb1-dev \
#         libxext-dev \
#         libxi-dev \
#         libxkbcommon-dev \
#         libxrender-dev \
#         libxslt1-dev \
#         libxss-dev \
#         libxtst-dev \
#         net-tools \
#         # omxplayer \
#         psmisc \
#         python-dev \
#         python-gobject \
#         python-netifaces \
#         python-pip \
#         python-setuptools \
#         vlc \
#         ttf-wqy-zenhei \
#         fonts-arphic-uming \
#         sqlite3 && \
#     apt-get clean

WORKDIR /usr/src/app
COPY ./assets/first-youtube-video.mp4 .

# RUN useradd -g video viewer

RUN useradd -ms "/bin/bash" viewer && \
    usermod -aG video viewer && \
    passwd -d viewer

USER viewer
