version: "2"
services:
  test-main:
    image: nicomiguelino/test-main
    build:
      context: .
      dockerfile: Dockerfile.test
    command: bash
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src/app
