FROM balenalib/raspberrypi3:buster

RUN apt-get update && \
    apt-get -y install \
        vlc

WORKDIR /usr/src/app
COPY ./assets/first-youtube-video.mp4 .

RUN useradd -ms "/bin/bash" viewer && \
    sudo usermod -aG video,sudo viewer && \
    passwd -d viewer

USER viewer
