name: 'Deploy Docker Images'

on:
  push:
    branches:
      - main
    paths:
      - 'e2e-ci-poc/**'
      - '.github/workflows/deploy-images.yml'
      - '!**/README.md'

jobs:
  build-images:
    runs-on: 'ubuntu-latest'
    defaults:
      run:
        working-directory: ./e2e-ci-poc
    steps:
      - name: 'Checkout the repository.'
        uses: actions/checkout@v3
