name: 'Deploy Docker Images'

on:
  push:
    branches:
      - main
    paths:
      - 'e2e-ci-poc/**'
      - '.github/workflows/deploy-images.yml'
      - '!**/README.md'

jobs:
  build-images:
    strategy:
      matrix:
        board: ['pi4']
    runs-on: 'ubuntu-latest'
    defaults:
      run:
        working-directory: ./e2e-ci-poc
    steps:
      - name: 'Checkout the repository.'
        uses: actions/checkout@v3
      - name: 'Set variables necessary for tagging Docker images.'
        run: |
          echo "GIT_SHORT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: 'Display details of the current working directory.'
        run: |
          echo "Current Working Directory: $PWD"
          echo "Directory Contents: "
          ls -la
      - name: 'Build the Docker images.'
        run: |
          services=(
            base
            publisher
            subscriber
          )

          # TODO: Remove the two echo statements below after debugging.
          echo "matrix.board: ${{ matrix.board }}"
          echo "matrix.board: ${ matrix.board }"

          for container in ${services[@]}; do
            path=$(readlink -f "Dockerfile.${container}")

            if [[ ! -f "${path}" ]]; then
              continue
              echo "Path $path does not exist. Skipping..."
            fi

            echo "Dockerfile Path: ${path}"
          done
