name: 'Deploy Docker Images'

on:
  push:
    branches:
      - main
    paths:
      - 'e2e-ci-poc/**'
      - '.github/workflows/deploy-images.yml'
      - '!**/README.md'

jobs:
  build-images:
    strategy:
      matrix:
        board: [pi3, pi4]
    runs-on: 'ubuntu-latest'
    defaults:
      run:
        working-directory: ./e2e-ci-poc
    steps:
      - name: 'Checkout the repository.'
        uses: actions/checkout@v3
      - name: 'Set variables necessary for tagging Docker images.'
        run: |
          echo "GIT_SHORT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Print out some values (for debugging purposes).
        run: |
          echo "matrix.board: ${{ matrix.board }}"
          echo "GIT_SHORT_HASH: $GIT_SHORT_HASH"
